spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_phicen
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
